yarnPath: .yarn/releases/yarn-3.1.1.cjs
enableGlobalCache: true

nodeLinker: node-modules

initFields:
  license: 'UNLICENSED'
  main: 'index.js'
  repository:
    type: 'git'
    url: 'git+https://github.com/es50678/yarn-v2-hello.git'
  publishConfig:
    registry: 'https://npm.pkg.github.com/'
  files:
    - '**/*.d.ts'
    - '**/*.js'
